[project]
name = "particles-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ncca-ngl>=0.2.7",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
